<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mymetamodel" nsURI="mymetamodel1" nsPrefix="mmm">
  <eClassifiers xsi:type="ecore:EClass" name="HTML">
    <eStructuralFeatures xsi:type="ecore:EReference" name="balise" lowerBound="1"
        upperBound="-1" eType="#//Balise" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Balise">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom : Balise_type"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="balise" upperBound="-1"
        eType="#//Balise"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="atribut" upperBound="-1"
        eType="#//Atribut"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Balise_type" instanceClassName="-&lt;title>&lt;/title>"/>
  <eClassifiers xsi:type="ecore:EClass" name="Atribut">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom : Attribut_type"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Attribut_type" instanceClassName="-class"/>
</ecore:EPackage>
