<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ovy2html" nsURI="http://www.example.org/ovy2html" nsPrefix="ovy2html">
  <eClassifiers xsi:type="ecore:EClass" name="HTML">
    <eStructuralFeatures xsi:type="ecore:EReference" name="balise" lowerBound="1"
        upperBound="-1" eType="#//Balise" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Balise" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="paragraphe" eType="#//Paragraphe"
        eOpposite="#//Paragraphe/balise"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="titre" lowerBound="1" upperBound="-1"
        eType="#//Titre" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="grandtitre" eType="#//GrandTitre"
        eOpposite="#//GrandTitre/balise"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GrandTitre">
    <eStructuralFeatures xsi:type="ecore:EReference" name="balise" eType="#//Balise"
        eOpposite="#//Balise/grandtitre"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Paragraphe">
    <eStructuralFeatures xsi:type="ecore:EReference" name="balise" eType="#//Balise"
        eOpposite="#//Balise/paragraphe"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Titre">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
