/**
 *
 * $Id$
 */
package HtmlMetaModel.validation;

import HtmlMetaModel.Attribut;
import HtmlMetaModel.Balise;
import HtmlMetaModel.Balise_Type;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link HtmlMetaModel.Balise}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BaliseValidator {
	boolean validate();

	boolean validateAttribut(EList<Attribut> value);
	boolean validateBalise(EList<Balise> value);
	boolean validateNom(EList<Balise_Type> value);
}
